cls
@echo off
echo Compiling...
g++.exe -Wall -g -I"C:\Program Files\CodeBlocks\MinGW\x86_64-w64-mingw32\include" -c D:\dev\OpenGL\project-scene3\test.cpp -o obj\Debug\test.o
echo Linking...
g++.exe -L"C:\Program Files\CodeBlocks\MinGW\x86_64-w64-mingw32\lib" -o bin\Debug\test.exe obj\Debug\test.o -lfreeglut -lopengl32 -lglu32 -lwinmm -lgdi32
echo Running...
bin\Debug\test.exe